FROM node:20-alpine
RUN apk add git
ARG CACHEBUST=2
ARG SECRETENV_BUNDLE
ARG SECRETENV_KEY
RUN echo SECRETENV_BUNDLE=$SECRETENV_BUNDLE
RUN echo SECRETENV_KEY=$SECRETENV_KEY
EXPOSE $PORT
WORKDIR /usr/src/app
COPY package*.json ./
RUN yarn install
COPY . .
RUN yarn test
CMD [ "yarn", "start"]