"""Reference test for the transfer-back summariser pattern
(docs/transfer-back-plan.md WP1.3).

A takeover agent carries a ``summarise_call`` function — builtin platform
``subagent`` targeting a ``text:`` summariser in the agent set — whose
transcript parameters are ``source: "metadata"`` reads of the
``aplisay.transfer.*`` keys seeded by ``prepare_takeover``. The transcripts
therefore flow OUT-OF-BAND: they are resolved by the worker's parameter
layer and handed to the subagent invocation without ever entering the
takeover model's context; only the summary (the tool result) comes back in.

This suite pins that chain end to end at the unit level:
``build_agent_tools`` → ``function_handler`` parameter resolution →
``on_subagent`` receiving the resolved transcript args.
"""

from __future__ import annotations

import asyncio

from pipecat_aplisay.agent_tools import build_agent_tools

SUMMARISER = "99999999-8888-7777-6666-555555555555"

BRIDGE_TRANSCRIPT = (
    "> caller: Yes, same banging as last winter.\n"
    "> transfer target: OK, I can come back Tuesday afternoon and swap the valve.\n"
)
PARENT_TRANSCRIPT = "> caller: Hi, my boiler is banging again.\n> agent: Let me get the engineer.\n"


def summarise_call_function():
    return {
        "name": "summarise_call",
        "description": "Summarise the conversations that led to this call",
        "implementation": "builtin",
        "platform": "subagent",
        "input_schema": {
            "type": "object",
            "properties": {
                "agent": {"type": "string", "source": "static", "from": SUMMARISER},
                "bridgeTranscript": {
                    "type": "string",
                    "source": "metadata",
                    "from": "aplisay.transfer.bridgeTranscript",
                },
                "parentTranscript": {
                    "type": "string",
                    "source": "metadata",
                    "from": "aplisay.transfer.parentTranscript",
                },
                "focus": {
                    "type": "string",
                    "description": "What the summary should concentrate on",
                },
            },
        },
    }


def build(metadata: dict, captured: list):
    async def on_subagent(args: dict, meta: dict):
        captured.append((args, meta))
        return {"summary": "Engineer returns Tuesday afternoon to swap the valve."}

    async def noop(*_a, **_k):
        return None

    return build_agent_tools(
        agent={"functions": [summarise_call_function()], "keys": []},
        metadata=metadata,
        send_message=noop,
        on_hangup=noop,
        on_transfer=noop,
        get_transfer_state=lambda: {},
        on_subagent=on_subagent,
    )


class TestSummariserPattern:
    def test_metadata_params_flow_out_of_band_to_subagent(self):
        metadata = {
            "aplisay": {
                "transfer": {
                    "bridgeTranscript": BRIDGE_TRANSCRIPT,
                    "parentTranscript": PARENT_TRANSCRIPT,
                    "key": "1",
                }
            }
        }
        captured: list = []
        [descriptor] = build(metadata, captured)

        result = asyncio.run(descriptor["execute"]({"focus": "agreed actions"}))

        assert result == {
            "summary": "Engineer returns Tuesday afternoon to swap the valve."
        }
        [(args, meta)] = captured
        # Transcripts resolved from aplisay.transfer.* and delivered to the
        # subagent invocation — never generated by (or shown to) the LLM.
        assert args["bridgeTranscript"] == BRIDGE_TRANSCRIPT
        assert args["parentTranscript"] == PARENT_TRANSCRIPT
        assert args["agent"] == SUMMARISER
        assert args["focus"] == "agreed actions"
        assert meta is metadata

    def test_llm_schema_hides_metadata_and_static_params(self):
        [descriptor] = build({}, [])
        visible = descriptor["schema"]["properties"]
        # Only the generated param is LLM-visible; the transcript carries and
        # the target agent are platform-wired.
        assert set(visible) == {"focus"}
        assert descriptor["kind"] == "subagent"

    def test_absent_transfer_metadata_omits_params(self):
        captured: list = []
        [descriptor] = build({"aplisay": {}}, captured)
        asyncio.run(descriptor["execute"]({}))
        [(args, _meta)] = captured
        # Missing metadata paths are OMITTED (never null) — a summariser
        # invoked on a call with no carried context simply gets no transcripts.
        assert "bridgeTranscript" not in args
        assert "parentTranscript" not in args
        assert args["agent"] == SUMMARISER
