steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '--build-arg'
      - SECRETENV_BUNDLE
      - '--build-arg'
      - SECRETENV_KEY
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/containers/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/containers/$REPO_NAME/$_SERVICE_NAME:staging
      - .
      - '-f'
      - Dockerfile
    id: Build
    secretEnv:
      - SECRETENV_BUNDLE
      - SECRETENV_KEY
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '--all-tags'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/containers/$REPO_NAME/$_SERVICE_NAME
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - llm-agent-staging
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/containers/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/containers/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - llm-agent-staging
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/SECRETENV__STAGINGBUNDLE/versions/latest
      env: SECRETENV_BUNDLE
    - versionName: projects/$PROJECT_ID/secrets/SECRETENV_STAGING_KEY/versions/latest
      env: SECRETENV_KEY
