steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '--build-arg'
      - SECRETENV_BUNDLE
      - '--build-arg'
      - SECRETENV_KEY
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/containers/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/containers/$REPO_NAME/$_SERVICE_NAME:staging
      - '-f'
      - agents/livekit/Dockerfile
      - .
    id: Build
    secretEnv:
      - SECRETENV_BUNDLE
      - SECRETENV_KEY
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '--all-tags'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/containers/$REPO_NAME/$_SERVICE_NAME
    id: Push
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/containers/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _SERVICE_NAME: livekit-agent-staging
  _DEPLOY_REGION: $LOCATION
  _AR_HOSTNAME: $LOCATION-docker.pkg.dev
tags:
  - livekit-agent-staging
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/SECRETENV_BUNDLE/versions/latest
      env: SECRETENV_BUNDLE
    - versionName: projects/$PROJECT_ID/secrets/SECRETENV_KEY/versions/latest
      env: SECRETENV_KEY
