package secretenv

import (
	"os"
	"testing"
)

// Fixture generated by the real Node package (github.com/rjp44/secretenv):
//
//	SECRETENV_KEY=go-vector-key
//	printf 'OPENAI_API_KEY=sk-test-12345\nPIPECAT_SIP_PASSWORD=p@ss:word/with+specials==\nSIPBRIDGE_API_TOKEN=deadbeefcafebabe\n' > .env
//	SECRETENV_KEY=go-vector-key npx secretenv -e
//
// This pins wire-compatibility: if the Go decryption ever diverges from the Node
// implementation, this test fails.
const (
	vectorKey    = "go-vector-key"
	vectorBundle = "d1b3386ae4ed260a7a4265583f91196b:cEsHs85c4Ym3lmxRxxXgv+7sW452MU/4kZ9GbNcCFeuOMfqPKG1jBWIMvCFV54EYfi4xKnahqFqWTg5ahtjv5C3xKuJAr+BiYJxhDy8NnC/vfryJqXzej5gpBd/1og2eufojyHsK88fFJUiWdX1kpk+EolJOV5NOBJkaPFRAbm0="
)

var vectorWant = map[string]string{
	"OPENAI_API_KEY":       "sk-test-12345",
	"PIPECAT_SIP_PASSWORD": "p@ss:word/with+specials==", // colons here must NOT confuse the iv:ct split
	"SIPBRIDGE_API_TOKEN":  "deadbeefcafebabe",
}

func TestDecryptMatchesNode(t *testing.T) {
	got, err := Decrypt(vectorBundle, vectorKey)
	if err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	if len(got) != len(vectorWant) {
		t.Fatalf("got %d vars, want %d: %v", len(got), len(vectorWant), got)
	}
	for k, want := range vectorWant {
		if got[k] != want {
			t.Errorf("%s = %q, want %q", k, got[k], want)
		}
	}
}

func TestDecryptWrongKeyFails(t *testing.T) {
	if _, err := Decrypt(vectorBundle, "not-the-key"); err == nil {
		t.Fatal("expected error decrypting with the wrong key, got nil")
	}
}

func TestDecryptMalformedBundle(t *testing.T) {
	for _, b := range []string{"", "nocolon", "zz:not-base64!!", "deadbeef:"} {
		if _, err := Decrypt(b, vectorKey); err == nil {
			t.Errorf("Decrypt(%q) = nil error, want error", b)
		}
	}
}

func TestLoadSetsEnvAndIsNoOpWhenUnset(t *testing.T) {
	t.Setenv("SECRETENV_KEY", vectorKey)
	t.Setenv("SECRETENV_BUNDLE", vectorBundle)
	if err := Load(); err != nil {
		t.Fatalf("Load: %v", err)
	}
	if got := os.Getenv("PIPECAT_SIP_PASSWORD"); got != vectorWant["PIPECAT_SIP_PASSWORD"] {
		t.Errorf("env PIPECAT_SIP_PASSWORD = %q, want %q", got, vectorWant["PIPECAT_SIP_PASSWORD"])
	}

	// No key/bundle -> no error, no change.
	t.Setenv("SECRETENV_KEY", "")
	t.Setenv("SECRETENV_BUNDLE", "")
	if err := Load(); err != nil {
		t.Fatalf("Load (unset) should be a no-op, got: %v", err)
	}
}
